### ISSUE TITLE
Create a Dashboard component

### ISSUE THREAD

**Issue by chrislaupama** [kahikatea-2019/MOA#16]
We need a component to hold our dashboard. _Think about whether this is likely to be functional or class based._ Let's get that created and so all of the child components for our dashboard can have a parent.
You may also need to ensure that this component has a client-side route set up too. 

Tasks:
- [x] Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [x] Create component file. 
- [x] Write some text we can see to insure this component renders.
- [ ] Create client-side route for component. 
- [ ] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

**Comment by Eteroa123** [comment]
![image](https://user-images.githubusercontent.com/18017602/57050586-83666000-6cd1-11e9-9c36-7447a83292ed.png)


Kia ora ! Ete here im assigned to ticket **"Create a Header Component #19**" :  https://github.com/kahikatea-2019/MOA/issues/19 

In order to finish my ticket I need the dashboard component! Let us know when you have completed this!!!!!!!
